#
##
## gluster-logging-metrics-preparation.yaml: Playbook to prepare OpenShift infrastructure for deployment of
##                                           Gluster-backed metrics and logging
##
## NOTE: Make sure to 'oc login' as cluster admin user to be able to
##       complete gluster set up.
##
## Available parameters:
##
##   - Remove previous volume/endpoints/service attempts:
##     ansible-playbook -i hosts gluster-logging-metrics-preparation.yaml
##
##
#


- hosts: infranodes
  gather_facts: true
  tasks:
  - name: get facts
    shell: uptime

- hosts: localhost
  connection: local

  vars:
    delete_current: false
  
  tasks:
  - name: Validate OC is installed and logged in
    shell: /usr/bin/oc whoami
    register: whoami
    failed_when: whoami.rc != 0

  - set_fact:
      storage_project: "{{ storage_project | default(hostvars[groups['masters'][0]]['gs_gluster_storage_project']) }}"

  - set_fact:
      gs_heketi_api_admin_key: "{{ hostvars[groups['masters'][0]]['gs_heketi_api_admin_key'] }}"

  - set_fact:
      gs_gluster_logging_metrics_block_host_gb: "{{ hostvars[groups['masters'][0]]['gs_gluster_logging_metrics_block_host_gb'] }}"

  - name: Switch to default project 
    shell: oc project default

  - name: encode heketi_secret
    shell: "echo -n {{ gs_heketi_api_admin_key }} | /usr/bin/base64"
    register: gs_heketi_secret_base64

  - name: Create heketi secret yaml
    template:
      src: templates/heketi/glusterfs-secret.yaml.j2
      dest: /tmp/glusterfs-secret.yaml

  - name: Import heketi secret yaml
    shell: cat /tmp/glusterfs-secret.yaml | oc create -f -

  - name: Get Heketi route from storage project
    shell: /usr/bin/oc get route heketi -n {{ storage_project }} -o jsonpath='{.spec.host}'
    register: heketi_route

  - name: Create storageclass definition
    template: 
      src: templates/heketi/glusterfs-block-storageclass.yaml.j2
      dest: /tmp/glusterfs-block-storageclass.yaml

  - name: Import storageclass definition
    shell: oc create -f /tmp/glusterfs-block-storageclass.yaml

  - name: Create block-hosting-volume for logging/metrics
    shell: /usr/bin/heketi-cli -s http://{{ heketi_route.stdout }} --user admin --secret {{ gs_heketi_api_admin_key }} volume create --size {{ gs_gluster_logging_metrics_block_host_gb }} --block
